#!/bin/bash

# This test file will be executed against the 'latest' scenario in scenarios.json,
# which installs the 'structurizr-cli' feature with default options alongside the
# java feature - so unlike the autogenerated test.sh, a JDK is present here and
# the CLI can actually be run.

set -e

# Optional: Import test library bundled with the devcontainer CLI
source dev-container-features-test-lib

# Feature-specific tests
# The 'check' command comes from the dev-container-features-test-lib.
# No exact version is asserted: this scenario tracks "latest", so the released
# version changes over time. 'past_release' pins an exact version instead.
check "execute command" bash -c "structurizr.sh version | grep 'structurizr-cli:'"

# Report results
# If any of the checks above exited with a non-zero exit code, the test will fail.
reportResults
