#!/bin/bash

# Executed against the 'explicit_toggles' scenario: every plugin toggle forced
# on while none of the required tools are present. The explicit values must
# beat detection, the install must warn rather than fail, and the config must
# carry what was asked for.
#
# For more information, see: https://github.com/devcontainers/cli/blob/main/docs/features/test.md
#
# This test can be run with the following command:
#
#    devcontainer features test -f superfile --skip-autogenerated --skip-duplicated .

set -e

# Optional: Import test library bundled with the devcontainer CLI
# See https://github.com/devcontainers/cli/blob/HEAD/docs/features/test.md#dev-container-features-test-lib
source dev-container-features-test-lib

CONFIG="${HOME}/.config/superfile/config.toml"

check "spf is on PATH" bash -c "command -v spf"

# A forced-on toggle whose binary is missing warns, but must never fail the
# build - the tool may be added later, by a subsequent Feature or at runtime.
check "metadata forced on" bash -c "grep -qx 'metadata = true' '${CONFIG}'"
check "code previewer forced to bat" bash -c "grep -qx 'code_previewer = \"bat\"' '${CONFIG}'"
check "zoxide support forced on" bash -c "grep -qx 'zoxide_support = true' '${CONFIG}'"

# Forcing the toggles must not have installed anything.
check "exiftool not installed" bash -c "! command -v exiftool"
check "zoxide not installed" bash -c "! command -v zoxide"

check "spf --debug-info runs" bash -c "spf --debug-info"

# Report results
reportResults
