#!/bin/bash

# This test file is executed against the 'pinned_without_config' scenario in
# scenarios.json: an exact version and no generated config, on a bare debian
# image that ships neither curl nor ca-certificates.
#
# For more information, see: https://github.com/devcontainers/cli/blob/main/docs/features/test.md
#
# This test can be run with the following command:
#
#    devcontainer features test -f superfile --skip-autogenerated --skip-duplicated .

set -e

# Optional: Import test library bundled with the devcontainer CLI
# See https://github.com/devcontainers/cli/blob/HEAD/docs/features/test.md#dev-container-features-test-lib
source dev-container-features-test-lib

check "spf is on PATH" bash -c "command -v spf"

# The pinned version must be the one that actually got installed.
check "pinned version installed" bash -c "spf --version | grep -q 'v1.6.0'"

# createAlias defaults to false -> upstream's command name only.
check "no superfile alias" bash -c "! test -e /usr/local/bin/superfile"

# configureDefaults: false -> the Feature must not write into the user's home.
check "no config written by the feature" bash -c "! test -e \"\${HOME}/.config/superfile/config.toml\""
check "no cd_on_quit wrapper" bash -c "! test -e /usr/local/share/superfile/cd_on_quit.sh"

# Without a generated config superfile still has to start up and fall back to
# its own built-in defaults.
check "spf path-list runs" bash -c "spf path-list"
check "spf --debug-info runs" bash -c "spf --debug-info"

# Report results
reportResults
