#!/bin/bash

# This test file will be executed against an auto-generated devcontainer.json that
# includes the 'superfile' Feature with no options.
#
# For more information, see: https://github.com/devcontainers/cli/blob/main/docs/features/test.md
#
# This test can be run with the following command:
#
#    devcontainer features test \
#                   --features superfile \
#                   --remote-user root \
#                   --skip-scenarios   \
#                   --base-image mcr.microsoft.com/devcontainers/base:ubuntu \
#                   /path/to/this/repo

set -e

# Optional: Import test library bundled with the devcontainer CLI
# See https://github.com/devcontainers/cli/blob/HEAD/docs/features/test.md#dev-container-features-test-lib
# Provides the 'check' and 'reportResults' commands.
source dev-container-features-test-lib

CONFIG="${HOME}/.config/superfile/config.toml"

# Feature-specific tests
# The 'check' command comes from the dev-container-features-test-lib. Syntax is...
# check <LABEL> <cmd> [args...]
check "spf is on PATH" bash -c "command -v spf"
check "spf --version" bash -c "spf --version"

# createAlias is off by default, so only upstream's command name exists.
check "no superfile alias by default" bash -c "! test -e /usr/local/bin/superfile"

# Both of these exercise the real binary without needing a TTY (the TUI itself
# cannot start in a test harness).
check "spf path-list runs" bash -c "spf path-list"
check "spf --debug-info runs" bash -c "spf --debug-info"

# configureDefaults defaults to true, so the remote user gets a config.
check "config generated for the remote user" bash -c "test -f '${CONFIG}'"
check "config is owned by the remote user" bash -c "test -O '${CONFIG}'"
check "auto update check disabled" bash -c "grep -qx 'auto_check_update = false' '${CONFIG}'"

# The generated config is deliberately partial - without this key superfile
# prints a 'missing fields' warning on every start.
check "missing-field warning suppressed" bash -c "grep -qx 'ignore_missing_fields = true' '${CONFIG}'"

check "nerdfont off by default" bash -c "grep -qx 'nerdfont = false' '${CONFIG}'"
check "cd_on_quit off by default" bash -c "grep -qx 'cd_on_quit = false' '${CONFIG}'"

# Plugin toggles default to 'auto', which follows what is actually on PATH.
# Assert that contract rather than fixed values: a base image that happens to
# ship one of these tools should flip the matching toggle, not fail the test.
# (None of the CI base images ship them today, so in practice these assert the
# off state - but they stay correct if that ever changes.)
check "metadata follows exiftool on PATH" bash -c "
    if command -v exiftool >/dev/null 2>&1; then
        grep -qx 'metadata = true' '${CONFIG}'
    else
        grep -qx 'metadata = false' '${CONFIG}'
    fi"
check "code previewer follows bat on PATH" bash -c "
    if command -v bat >/dev/null 2>&1; then
        grep -qx 'code_previewer = \"bat\"' '${CONFIG}'
    else
        grep -qx 'code_previewer = \"\"' '${CONFIG}'
    fi"
check "zoxide support follows zoxide on PATH" bash -c "
    if command -v zoxide >/dev/null 2>&1; then
        grep -qx 'zoxide_support = true' '${CONFIG}'
    else
        grep -qx 'zoxide_support = false' '${CONFIG}'
    fi"

# cdOnQuit is opt-in, so nothing should have been added to the shell rc files.
check "no cd_on_quit wrapper by default" bash -c "! test -e /usr/local/share/superfile/cd_on_quit.sh"
check "shell rc files untouched" bash -c "! grep -qF 'superfile devcontainer feature' '${HOME}/.bashrc' 2>/dev/null"

# superfile writes hotkeys.toml/theme itself on first run - it must not have
# replaced the config file this Feature generated.
check "feature config survives superfile" bash -c "grep -q 'Generated by the .superfile. Dev Container Feature' '${CONFIG}'"

# Report results
# If any of the checks above exited with a non-zero exit code, the test will fail.
reportResults
