#!/bin/bash

# Executed against the 'tools_from_dockerfile' scenario, whose Dockerfile
# apt-installs exiftool and zoxide before the Feature is layered on top, with
# every install* option left at its default (false).
#
# This is the regression test for plugin detection: the toggles must follow
# what is on PATH, whoever installed it, so an image that already ships the
# tools gets the plugins WITHOUT the Feature re-installing a preview toolchain.
#
# For more information, see: https://github.com/devcontainers/cli/blob/main/docs/features/test.md
#
# This test can be run with the following command:
#
#    devcontainer features test -f superfile --skip-autogenerated --skip-duplicated .

set -e

# Optional: Import test library bundled with the devcontainer CLI
# See https://github.com/devcontainers/cli/blob/HEAD/docs/features/test.md#dev-container-features-test-lib
source dev-container-features-test-lib

CONFIG="${HOME}/.config/superfile/config.toml"

check "spf is on PATH" bash -c "command -v spf"

# Provided by the image's Dockerfile, not by this Feature.
check "exiftool present from the image" bash -c "command -v exiftool"
check "zoxide present from the image" bash -c "command -v zoxide"

# The point of the change: plugins on, without installPreviewTools.
check "metadata enabled from detected exiftool" bash -c "grep -qx 'metadata = true' '${CONFIG}'"
check "zoxide support enabled from detected zoxide" bash -c "grep -qx 'zoxide_support = true' '${CONFIG}'"

# Detection is per-tool: bat was deliberately not installed, so the code
# previewer must stay on superfile's builtin chroma highlighter.
check "bat absent" bash -c "! command -v bat"
check "code previewer left builtin without bat" bash -c "grep -qx 'code_previewer = \"\"' '${CONFIG}'"

# The Feature must NOT have installed the preview toolchain to achieve the
# above - that is the whole cost this decoupling avoids.
check "ffmpeg not installed by the feature" bash -c "! command -v ffmpeg"
check "pdftoppm not installed by the feature" bash -c "! command -v pdftoppm"

# superfile must still start against the generated config.
check "spf path-list runs" bash -c "spf path-list"
check "spf --debug-info runs" bash -c "spf --debug-info"

# Report results
reportResults
