#!/bin/bash

# This test file is executed against the 'with_all_extras' scenario in
# scenarios.json: every optional tool installed, cd_on_quit enabled and Nerd
# Font glyphs turned off. It covers everything the auto-generated (no-options)
# test cannot reach.
#
# For more information, see: https://github.com/devcontainers/cli/blob/main/docs/features/test.md
#
# This test can be run with the following command:
#
#    devcontainer features test -f superfile --skip-autogenerated --skip-duplicated .

set -e

# Optional: Import test library bundled with the devcontainer CLI
# See https://github.com/devcontainers/cli/blob/HEAD/docs/features/test.md#dev-container-features-test-lib
source dev-container-features-test-lib

CONFIG="${HOME}/.config/superfile/config.toml"

check "spf is on PATH" bash -c "command -v spf"

# createAlias: true (the Feature defaults it to false)
check "superfile alias installed" bash -c "test -L /usr/local/bin/superfile && superfile --version"

# installPreviewTools. Note 'bat' is packaged as 'batcat' on Debian/Ubuntu -
# superfile calls 'bat', so the Feature has to bridge the two names.
check "ffmpeg installed" bash -c "command -v ffmpeg"
check "pdftoppm installed" bash -c "command -v pdftoppm"
check "exiftool installed" bash -c "command -v exiftool"
check "bat callable under the name superfile uses" bash -c "bat --version"

# installClipboardTools
check "xdg-open installed" bash -c "command -v xdg-open"
check "xclip installed" bash -c "command -v xclip"
check "wl-copy installed" bash -c "command -v wl-copy"

# installZoxide
check "zoxide installed" bash -c "command -v zoxide"

# Plugin toggles default to 'auto' and follow what is on PATH - here the
# tools this Feature just installed, so all three resolve on.
check "metadata plugin enabled" bash -c "grep -qx 'metadata = true' '${CONFIG}'"
check "bat wired as code previewer" bash -c "grep -qx 'code_previewer = \"bat\"' '${CONFIG}'"
check "zoxide support enabled" bash -c "grep -qx 'zoxide_support = true' '${CONFIG}'"

# nerdfont: true (the Feature defaults it to false)
check "nerdfont enabled" bash -c "grep -qx 'nerdfont = true' '${CONFIG}'"

# cdOnQuit: true - config flag plus the shell wrapper.
check "cd_on_quit enabled in config" bash -c "grep -qx 'cd_on_quit = true' '${CONFIG}'"
check "cd_on_quit wrapper installed" bash -c "test -f /usr/local/share/superfile/cd_on_quit.sh"
check "cd_on_quit wrapper sourced from .bashrc" bash -c "grep -qF 'superfile devcontainer feature' '${HOME}/.bashrc'"
check "wrapper defines the spf shell function" bash -c ". /usr/local/share/superfile/cd_on_quit.sh && [ \"\$(type -t spf)\" = 'function' ]"

# The wrapper must not shadow the binary into oblivion - 'command spf' still
# has to reach the real executable, which is what the wrapper calls.
check "real spf still reachable through the wrapper" bash -c ". /usr/local/share/superfile/cd_on_quit.sh && command spf --version"

# superfile has to be able to actually read the config we generated.
check "spf --debug-info runs" bash -c "spf --debug-info"
check "spf reports the installed dependencies" bash -c "spf --debug-info | grep -A20 Dependencies | grep exiftool | grep -qv 'Not Found'"

# Report results
reportResults
