#!/bin/bash

# This test file is executed against the 'with_node' scenario in scenarios.json,
# which pairs 'pi-dev' with the 'node' Feature - pi-dev hard-requires Node.js
# >=22.19.0 and npm to already be present, so it cannot be tested with the
# plain auto-generated (no-Features) test.
#
# For more information, see: https://github.com/devcontainers/cli/blob/main/docs/features/test.md
#
# This test can be run with the following command:
#
#    devcontainer features test -f pi-dev --skip-autogenerated --skip-duplicated .

set -e

source dev-container-features-test-lib

check "pi is on PATH" bash -c "command -v pi"
check "pi --version" bash -c "pi --version"

reportResults
