#!/bin/bash

# This test file is executed against the 'with_uv_python' scenario in scenarios.json,
# which runs 'speckit' on an image that already ships uv + Python. speckit assumes both
# are present and does not install them, so it cannot be exercised by the plain
# auto-generated (no-Features) test.
#
# For more information, see: https://github.com/devcontainers/cli/blob/main/docs/features/test.md
#
# This test can be run with the following command:
#
#    devcontainer features test -f speckit --skip-autogenerated --skip-duplicated .

set -e

# Optional: Import test library bundled with the devcontainer CLI
# See https://github.com/devcontainers/cli/blob/HEAD/docs/features/test.md#dev-container-features-test-lib
source dev-container-features-test-lib

# Feature-specific tests
check "specify is on PATH" bash -c "command -v specify"
check "specify --help" bash -c "specify --help"

# Report results
reportResults
