#!/bin/bash

# This test file will be executed against an auto-generated devcontainer.json that
# includes the 'herdr' Feature with no options.
#
# For more information, see: https://github.com/devcontainers/cli/blob/main/docs/features/test.md
#
# This test can be run with the following command:
#
#    devcontainer features test \
#                   --features herdr \
#                   --remote-user root \
#                   --skip-scenarios   \
#                   --base-image mcr.microsoft.com/devcontainers/base:ubuntu \
#                   /path/to/this/repo

set -e

# Optional: Import test library bundled with the devcontainer CLI
# See https://github.com/devcontainers/cli/blob/HEAD/docs/features/test.md#dev-container-features-test-lib
# Provides the 'check' and 'reportResults' commands.
source dev-container-features-test-lib

CONFIG="${HOME}/.config/herdr/config.toml"
SKILL="${HOME}/.claude/skills/herdr/SKILL.md"
BASH_COMPLETION="/usr/share/bash-completion/completions/herdr"
ZSH_COMPLETION="/usr/local/share/zsh/site-functions/_herdr"
SERVER_LOG="${HOME}/.config/herdr/herdr-server.log"

# Feature-specific tests
# The 'check' command comes from the dev-container-features-test-lib. Syntax is...
# check <LABEL> <cmd> [args...]
check "herdr is on PATH" bash -c "command -v herdr"
check "herdr --version" bash -c "herdr --version"
check "installed at /usr/local/bin/herdr" bash -c "test -x /usr/local/bin/herdr"

# herdr's TUI needs a real terminal; these run headlessly and are the sane way
# to exercise the real binary in a test harness.
check "herdr status runs" bash -c "herdr status"
check "herdr --default-config runs" bash -c "herdr --default-config | grep -q '^\[update\]'"

# configureDefaults defaults to true, so the remote user gets a config.
check "config generated for the remote user" bash -c "test -f '${CONFIG}'"
check "config is owned by the remote user" bash -c "test -O '${CONFIG}'"
check "onboarding wizard disabled" bash -c "grep -qx 'onboarding = false' '${CONFIG}'"
check "background version check disabled" bash -c "grep -qx 'version_check = false' '${CONFIG}'"
check "background manifest check disabled" bash -c "grep -qx 'manifest_check = false' '${CONFIG}'"

# 'channel' is deliberately left unset so it keeps upstream's default. Prove
# both halves: absent from the file, still reported as stable by the binary.
check "update channel left at upstream default" bash -c "! grep -q '^channel' '${CONFIG}' && herdr status | grep -q 'channel: stable'"

# The strongest assertion available: start the real server, then read its own
# log. Without this config herdr logs an update check and an agent-manifest
# fetch against herdr.dev within seconds of startup.
check "server accepts the config and stays offline" bash -c '
    rm -f "'"${SERVER_LOG}"'"
    timeout 12 herdr server >/dev/null 2>&1 || true
    test -f "'"${SERVER_LOG}"'" || { echo "server wrote no log"; exit 1; }
    if grep -q "config parse error" "'"${SERVER_LOG}"'"; then
        echo "herdr rejected the generated config:"
        grep -A2 "config parse error" "'"${SERVER_LOG}"'"
        exit 1
    fi
    if grep -qiE "update check|manifest update|herdr\.dev" "'"${SERVER_LOG}"'"; then
        echo "herdr still called home despite the generated config:"
        grep -iE "update check|manifest update|herdr\.dev" "'"${SERVER_LOG}"'"
        exit 1
    fi'

# installSkill defaults to true.
check "agent skill installed" bash -c "test -f '${SKILL}'"
check "agent skill is owned by the remote user" bash -c "test -O '${SKILL}'"
check "agent skill has the herdr frontmatter" bash -c "head -3 '${SKILL}' | grep -qx 'name: herdr'"
# The skill is generated by the installed binary, so it matches the CLI that is
# actually present - it documents HERDR_ENV as its own guardrail.
check "agent skill carries the HERDR_ENV guardrail" bash -c "grep -q 'HERDR_ENV' '${SKILL}'"

# installCompletions defaults to true.
check "bash completion installed" bash -c "test -f '${BASH_COMPLETION}'"
check "zsh completion installed" bash -c "test -f '${ZSH_COMPLETION}'"
check "bash completion sources and registers herdr" bash -c "
    source '${BASH_COMPLETION}'
    complete -p herdr >/dev/null"
check "zsh completion is a compdef for herdr" bash -c "head -1 '${ZSH_COMPLETION}' | grep -qx '#compdef herdr'"

# Report results
# If any of the checks above exited with a non-zero exit code, the test will fail.
reportResults
